@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class node4 as "package  modulos.agregacion.controllers" << package >>
class node1 as "package  modulos.agregacion.converters" << package >>
class node3 as "package  modulos.agregacion.entities" << package >>
class node2 as "package  modulos.agregacion.repositories" << package >>
class node0 as "package  modulos.agregacion.services" << package >>

@enduml
