@startuml

'DATO DE COLOR: Los hechos son los archivos .csv
class Hecho {
    -titulo: String
    -descripcion: String
    -categoria: Categoria
    -contenidoMultimediaOpcional: TipoContenido
    -pais: Pais
    -fechaAcontecimiento: Date
    -fechaDeCarga: Date
    -origen: Origen
}

class Pais {
    -pais: String
}

enum Origen {
    CARGA_MANUAL
    DATASET
    'DATASET -> csv
    CONTRIBUYENTE
}

' La clase Fuente es necesaria a futuro ya que después habrán fuentes dinamicas y proxys
interface Fuente {
    +leerFuente(): Lista<Hecho>
}

class FuenteEstatica implements Fuente {
    ' dataSet sería el nombre del archivo csv
    -dataSet: String
    +leerFuente(): List<Hecho>
}


class FuenteDinamica implements Fuente {
    +leerFuente(): List<Hecho>
}

class FuenteProxy implements Fuente{
    +leerFuente(): List<Hecho>
}
class Coleccion {
    -titulo: String
    -descripcion: String
    -hechos: List<Hecho>
    -fuente: Fuente
    -criterio: List<Filtro>
}

' Clase para evitar parámetros largos a futuro
class DatosColeccion {
    -titulo: String
    -descripcion: String
    -fuente: Fuente
}

class Administrador {
    ' se almacenarán y quedarán a disposición de las personas administradoras.
    -listaContribuyentes: List<Contribuyente>
    +agregarContribuyente(contribuyente: Contribuyente)
    +listaContribuyentesContains(contribuyente: Contribuyente): Boolean
    +crearColeccion(datosColeccion: DatosColeccion, criterios: List<Filtro>, hechosTotales: List<Hecho>): List<Coleccion>
    +importarHechos(fuente: Fuente): List<Hecho>
    +evaluarSolicitudEliminacion(hecho: Hecho): Boolean
    '+etiquetarHecho(hecho: Hecho) etiqueta no sería el conjunto de filtros¿
    ' Se puede etiquetar al hecho si fue cargado por contribuyente
}

' Los publicadores pueden ser tanto el contribuyente como el visualizador
class Publicador {
    -datosPersonales: DatosPersonalesPublicador
    +subirHechos(quiereAnonimato: Boolean, hechos: List<Hecho>)
    ' En el caso del contribuyente, va a poder subir con sus datos personales
}


class Contribuyente extends Publicador{
    -cantHechosSubidos: Integer
    +solicitarEliminacion(hecho: Hecho)
}

class Visualizador extends Publicador{
    -filtros: List<Filtro>
    +navegarPorHechos()
    +aplicarFiltros(filtros: List<Filtro>): Set<Hecho>
}

class DatosPersonalesPublicador {
    -nombre: String
    -apellido: String
    -edad: Integer
}

Interface Filtro {
    +aprobarFiltro(hecho: Hecho): Boolean
}

class FiltroFechaAcontecimiento implements Filtro{
    -fechaInicial: ZonedDateTime
    -fechaFinal: ZonedDateTime
    +aprobarHecho(hecho: Hecho): Boolean
}
'Pais puede ser una clase o enum
class FiltroPais implements Filtro{
    -pais: Pais
    +aprobarHecho(hecho: Hecho): Boolean
}
'el titulo puede ser una clase o enum
class FiltroCategoria implements Filtro{
    -categoria: Categoria
    +aprobarHecho(hecho:Hecho): Boolean
}

class FiltroDescripcion implements Filtro{
    -Descripcion: String
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroTitulo implements Filtro{
    -Titulo: String
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroContenidoMultimedia implements Filtro{
    -tipoContenido: TipoContenido
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroFechaCarga implements Filtro{
    -fechaInicial: ZonedDateTime
    -fechaFinal: ZonedDateTime
    +aprobarHecho(Hecho: hecho): Boolean
}

class FiltroOrigen implements Filtro{
    -origen: Origen
    +aprobarHecho(Hecho: hecho): Boolean
}

'Todas las palabras de la descripcion del filtro deben
' estar contenidas en la descripcion del hecho para que
' devuelva true. (lo mismo con el titulo)

class Categoria{
    -titulo: String
}

class Geocodificador {
    +obtenerPais(Double: latitud, Double: longitud)
}

' Si bien no hay que almacenar en memoria los hechos, sirve para testear funciones
class Globales {
    +hechosTotales: List<Hecho>
    +solicitudesEliminacion: List<Hecho>
}

'lista de hechos: Fuegos locos
'[titulo, fecha]
'Fuegos locos -> titulos
'Fuegos locos filtrada por titulos -> fecha
'Fuegos locos filtrada por titulo y fecha

enum TipoContenido {
    TEXTO
    IMAGEN
    AUDIO
    VIDEO
}

'class ContenidoMultimedia {
'    -tipoContenido: Enum
'
'}
' -tipo: tipoDeHecho

' Una coleccion está compuesta por hechos
Coleccion *-- Hecho
' Un contribuyente sí o sí debe tener hechos asociados, sino no es un contribuyente
Contribuyente *-- Hecho

Pais --* Hecho

'Hecho --> ContenidoMultimedia

Hecho *-- TipoContenido

'ContenidoMultimedia *-- TipoContenido

Hecho *-- Categoria

Hecho *-- Origen

@enduml