@startuml

'CLASES DENTRO DE ENTITIES'
class Categoria{
    -titulo: String
}

class Coleccion {
    -activo: Boolean
    -id: Long
    -titulo: String
    -descripcion: String
    -hechos: List<Hecho>
    -fuente: Fuente
    -criterio: List<Filtro>
    +addCriterios(Filtro ... filtros)
    +addCriterios(filtros: List<Filtro>)
    +addHechos(Hecho ... hechos)
    +addHechos(hechos: List<Hecho>)
}

class DatosColeccion {
    -titulo: String
    -descripcion: String
    -fuente: Fuente
}

class Filtrador{
    +aplicarFiltros(filtros: List<Filtro>, hechos: List<Hecho>)
}

class Geocodificador {
    +obtenerPais(latitud: Double, longitud: Double)
}

class GestorRoles {
    +VisualizadorAContribuyente(usuario: Usuario): Boolean
    +ContribuyenteAVisualizador(usuario: Usuario): Boolean
}

class Hecho {
    -activo: Boolean
    -id: Long
    -titulo: String
    -descripcion: String
    -categoria: Categoria
    -contenidoMultimediaOpcional: TipoContenido
    -pais: Pais
    -fechaAcontecimiento: ZonedDateTime
    -fechaDeCarga: ZonedDateTime
    -origen: Origen
}

class LectorCSV {
    -dataSet: String
    -campos: List<String>
    +leerCSV(hechos: List<Hecho>): ModificadorHechos
    -filtrarColumnas(headers: List<String>): Integer
    -normalizar(texto: String): String
    -normalizarYComparar(s1: String, s2: String): Boolean
}

class LectorJSON{
}

class ModificadorHechos {
    -hechosASubir: List<Hecho>
    -hechosAModificar: List<Hecho>
}

enum Origen {
    CARGA_MANUAL
    DATASET
    CONTRIBUYENTE
}

class Pais {
    -pais: String
}

enum Permisos {
    ADMINISTRADOR
    CONSULTOR
}

class SolicitudHecho {
    -usuario: Usuario
    -hecho: Hecho
    -id: Long
}

enum TipoContenido {
    TEXTO
    IMAGEN
    AUDIO
    VIDEO
}

'-----------------------------------------------
'CLASES DENTRO DE cASOSdEuSO'
class NavegarPorHechos {
    +navegarPorHechos(filtros: List<Filtro>, coleccion: Coleccion)
    +navegarPorHechos(coleccion: Coleccion)
}

'-----------------------------------------------
'CLASES DENTRO DE FILTROS'

Interface Filtro {
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroCategoria implements Filtro {
    -categoria: Categoria
    +aprobarHecho(hecho:Hecho): Boolean
}

class FiltroContenidoMultimedia implements Filtro {
    -tipoContenido: TipoContenido
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroDescripcion implements Filtro {
    -descripcion: String
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroFechaAcontecimiento implements Filtro {
    -fechaInicial: ZonedDateTime
    -fechaFinal: ZonedDateTime
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroFechaCarga implements Filtro {
    -fechaInicial: ZonedDateTime
    -fechaFinal: ZonedDateTime
    +aprobarHecho(Hecho: hecho): Boolean
}

class FiltroOrigen implements Filtro {
    -origenDeseado: Origen
    +aprobarHecho(Hecho: hecho): Boolean
}

class FiltroPais implements Filtro {
    -pais: Pais
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroTitulo implements Filtro {
    -titulo: String
    +aprobarHecho(hecho: Hecho): Boolean
}

'-----------------------------------------------
'CLASES DENTRO DE FUENTES'
interface Fuente {
    +leerFuente(): ModificadorHechos
}

class FuenteDinamica implements Fuente {
    +leerFuente(): ModificadorHechos
}

class FuenteEstatica implements Fuente {
    -dataSet: String
    +leerFuente(): ModificadorHechos
}

' Para próximas entregas
class FuenteProxy implements Fuente{
    +leerFuente(): ModificadorHechos
}

'-----------------------------------------------
'CLASES DENTRO DE PERSONAS'

class DatosPersonalesPublicador {
    -id: Long
    -nombre: String
    -apellido: String
    -edad: Integer
}

enum Rol {
    VISUALIZADOR
    CONTRIBUYENTE
    ADMINISTRADOR
}

class Usuario {
    -contrasenia: String
    -id: Long
    -cantHechosSubidos: Integer
    -rol: Rol
    -datosPersonales: DatosPersonalesPublicador
    +incrementarHechosSubidos()
    +disminuirHechosSubidos()
}







' Relación Hechos

Coleccion *-- Hecho
Pais --* Hecho
Hecho --> TipoContenido
Hecho *-- Categoria
Hecho --> Origen
SolicitudHecho --* Hecho


' Relación entre Usuario y Rol
Usuario --> Rol

' Relacion entre NagevarPorHechos y Coleccion/Filtros
NavegarPorHechos --> Coleccion
NavegarPorHechos --> Filtro: *
'Creo que son flechas punteadas pero no sé como es la sintaxis

GestorRoles --* Usuario

' Relacion de Lectores
LectorCSV --> Hecho: *
LectorCSV --> ModificadorHechos

Filtrador --> Hecho: *
Filtrador --> Filtro: *

Coleccion *-- DatosColeccion
Usuario *-- DatosPersonalesPublicador



@enduml

class Persona{

}

class Administrador extends Visualizador {
    ' se almacenarán y quedarán a disposición de las personas administradoras.
    -listaContribuyentes: List<Contribuyente>
    'Subida manual del hecho
'    +subirHecho(Hecho: hecho)
'   +crearColeccion(datosColeccion: DatosColeccion, criterios: List<Filtro>, hechosTotales: List<Hecho>)
'   +importarHechos(fuente: Fuente)
'   +evaluarSolicitudEliminacion(solicitud: SolicitudHecho, respuesta: Boolean)
'   +evaluarSolicitudSubirHecho(solicitud: SolicitudHecho, respuesta: Boolean)
}



class aplicarFiltro{
}
' Agregar metodos, APLICAR FILTRO,...


class Contribuyente extends Visualizador {
    -cantHechosSubidos: Integer
    +incrementarHechosSubidos()
    +disminuirHechosSubidos()
    '+solicitarEliminacion(hecho: Hecho)
}



class Visualizador{
    -datosPersonales: DatosPersonalesPublicador
'    +solicitudSubirHecho(hecho: Hecho, GestorPersona: ContextoPersona)
    +navegarPorHechos(filtros: List<Filtro>, coleccion: Coleccion)
    +navegarPorHechos(coleccion: Coleccion)
    ' Llevarlo a clase
    -aplicarFiltros(filtros: List<Filtro>, coleccion: Coleccion): Set<Hecho>
}