@startuml

'-----------------------------------------------
'CLASES DENTRO DE BUSCADORES'

class BuscadorCategoria{
    +buscarOCrear(hechos: List<Hecho>, elemento: String): Categoria
    +buscar(hechos: List<Hecho>, elemento: String): Categoria

}

class BuscadorPais{
    +buscarOCrear(hechos: List<Hecho>, elemento: String): Pais
    +buscar(hechos: List<Hecho>, elemento: String): Pais
}

'-----------------------------------------------
'CLASES DENTRO DE ALGORITMOS DE CONSENSO'

Interface AlgoritmoConsenso {
    +ejecutarAlgoritmoConsenso(fuentes: List<Dataset>)
}

class AlgoritmoConsensoMayoriaAbsoluta implements AlgoritmoConsenso{
    -coleccion: Coleccion
    +ejecutarAlgoritmoConsenso(fuentes: List<Dataset>)
    +mapearIdsDatasets(fuentes: List<Dataset>): List<Long>
}

class AlgoritmoConsensoMayoriaSimple implements AlgoritmoConsenso{
    -coleccion: Coleccion
    +ejecutarAlgoritmoConsenso(fuentes: List<Dataset>)
    +mitadDeFuentesContienenHecho(hecho: Hecho, fuentes: List<Dataset>): List<Long>
}

class AlgoritmoConsensoMultiplesMenciones implements AlgoritmoConsenso{
    -coleccion: Coleccion
    +ejecutarAlgoritmoConsenso(fuentes: List<Dataset>)
    -dosFuentesContienenHecho(hecho: Hecho): Boolean
    -existeHechoIgualTituloDiferentesAtributos(hecho: Hecho, hechos: List<Hecho>)
    -tienenAtributosDistintos(h1: Hecho, h2: Hecho): Boolean
    }



'-----------------------------------------------
'CLASES DENTRO DE FILTROS'

Interface Filtro {
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroCategoria implements Filtro {
    -categoria: Categoria
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroContenidoMultimedia implements Filtro {
    -tipoContenido: TipoContenido
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroDescripcion implements Filtro {
    -descripcion: String
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroFechaAcontecimiento implements Filtro {
    -fechaInicial: ZonedDateTime
    -fechaFinal: ZonedDateTime
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroFechaCarga implements Filtro {
    -fechaInicial: ZonedDateTime
    -fechaFinal: ZonedDateTime
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroOrigen implements Filtro {
    -origenDeseado: Origen
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroPais implements Filtro {
    -pais: Pais
    +aprobarHecho(hecho: Hecho): Boolean
}

class FiltroTitulo implements Filtro {
    -titulo: String
    +aprobarHecho(hecho: Hecho): Boolean
}

'-----------------------------------------------
'CLASES DENTRO DE FUENTES'

class FuenteDinamica {
    +leerFuente(): ModificadorHechos
}

class FuenteEstatica {
    -dataSet: String
    +leerFuente(): ModificadorHechos
}

' Para próximas entregas
class FuenteProxy {
    -url_base: String
    -access_token: String
    +login(email: String, contraseña: String): Boolean
    +getHechos(hechosTotales: List<Hecho>): List<Hecho>
    +getHechoPorId(id: Integer, hechosTotales: List<Hecho>): Hecho
    +getHechosMetaMapa(url_1: String, filtros: FiltroHechosDTO, hechosTotales: List<Hecho>): List<Hecho>
    +getColeccionesMetaMapa(url_1: String, hechosTotales: List<Hecho>): List<Hecho>
    +getHechosDeColeccionMetaMapa(url_1: String, id: Long, hechosTotales: List<Hecho>): List<Hecho>
    +enviarSolicitudEliminacionMetaMapa(url_1: String, data: SolicitudHechoEliminarInputDTO)
}

'-----------------------------------------------
'CLASES DENTRO DE PERSONAS'

class DatosPersonalesPublicador {
    -id: Long
    -nombre: String
    -apellido: String
    -edad: Integer
}

enum Rol {
    VISUALIZADOR
    CONTRIBUYENTE
    ADMINISTRADOR
}

class Usuario {
    -contrasenia: String
    -id: Long
    -cantHechosSubidos: Integer
    -rol: Rol
    -datosPersonales: DatosPersonalesPublicador
    +incrementarHechosSubidos()
    +disminuirHechosSubidos()
}

'---------------------------------------------
'CLASES DENTRO DE ENTITIES'
class Categoria{
    -titulo: String
}

class Coleccion {
    -activo: Boolean
    -id: Long
    -titulo: String
    -descripcion: String
    -hechos: List<Hecho>
    -criterio: List<Filtro>
    +addCriterios(filtros ... Filtro)
    +addCriterios(filtros: List<Filtro>)
    +addHechos(hechos ... Hecho)
    +addHechos(hechos: List<Hecho>)
}

class FechaParser {
    -FORMATOS_LOCAL: List<DateTimeFormatter>
    -FORMATOS_ZONED: List<DateTimeFormatter>
    +parsearFecha(fechaStr: String): ZonedDateTime
}

class Filtrador{
    +aplicarFiltros(filtros: List<Filtro>, hechos: List<Hecho>)
    +hechoPasaFiltros(filtros: List<Filtro>, hecho: Hecho): Boolean
    +filtrarMensajes(mensajes: List<Mensaje>, id_usuario: Long): List<Mensaje>
}

class FiltrosColeccion {
    - filtroCategoria : FiltroCategoria
    - filtroPais : FiltroPais
    - filtroDescripcion : FiltroDescripcion
    - filtroContenidoMultimedia : FiltroContenidoMultimedia
    - filtroFechaAcontecimiento : FiltroFechaAcontecimiento
    - filtroFechaCarga : FiltroFechaCarga
    - filtroOrigen : FiltroOrigen
    - filtroTitulo : FiltroTitulo
}

class FormateadorHecho{
    +formatearAtributosHecho(hechosDinamica: List<Hecho>,hechosEstatica: List<Hecho>,hechosProxy: List<Hecho> , dtoInput: SolicitudHechoInputDTO ): AtributosHecho
    +formatearFiltrosColeccion(hechosDinamica: List<Hecho>, hechosEstatica: List<Hecho>, hechosProxy: List<Hecho>  , inputDTO: CriteriosColeccionDTO ): FiltrosColeccion
    +filtrosColeccionToString(filtros: Map<Class<? extends Filtro>, Filtro>): CriteriosColeccionDTO
    +obtenerMapaDeFiltros(filtrosColeccion: FiltrosColeccion): Map<Class<? extends Filtro>, Filtro>
}

class Geocodificador {
    +obtenerPais(latitud: Double, longitud: Double)
}

class GestorRoles {
    +VisualizadorAContribuyente(usuario: Usuario): Boolean
    +ContribuyenteAVisualizador(usuario: Usuario): Boolean
}

class Hecho {
    -activo: Boolean
    -id: Long
    -id_usuario: Long
    -titulo: String
    -descripcion: String
    -categoria: Categoria
    -contenidoMultimediaOpcional: TipoContenido
    -pais: Pais
    -fechaAcontecimiento: ZonedDateTime
    -fechaDeCarga: ZonedDateTime
    -origen: Origen
    -fechaUltimaActualizacion: ZonedDateTime
}

class LectorCSV {
    -dataSet: String
    -campos: List<String>
    +leerCSV(hechos: List<Hecho>): ModificadorHechos
    -filtrarColumnas(headers: List<String>): List<Integer>
}

class Mensaje{
    -id: Long
    -id_solicitud_hecho: Long
    -id_receptor: Long
    -textoMensaje: String
}

class ModificadorHechos {
    -hechosASubir: List<Hecho>
    -hechosAModificar: List<Hecho>
}

class Normalizador{
    +normalizar(texto: String): String
    +normalizarYComparar(s1: String, s2: String): Boolean
    +normalizarSeparado(texto: String)
}

enum Origen {
     FUENTE_DINAMICA
     FUENTE_ESTATICA
     CARGA_MANUAL
     FUENTE_PROXY_METAMAPA
}

class Pais {
    -pais: String
}

'RespuestaHttp

class SolicitudHecho {
    -usuario: Usuario
    -hecho: Hecho
    -id: Long
    -justificacion: String
    -procesada: boolean
    -rechazadaPorSpam: boolean
}

enum TipoContenido {
    INVALIDO
    TEXTO
    IMAGEN
    AUDIO
    VIDEO
}


' Relación Hechos

Coleccion *-- Hecho
Pais --* Hecho
Hecho --> TipoContenido
Hecho *-- Categoria
Hecho --> Origen
SolicitudHecho --* Hecho




' Relación entre Usuario y Rol
Usuario --> Rol

GestorRoles --* Usuario

' Relacion de Lectores
LectorCSV --> Hecho
LectorCSV --> ModificadorHechos
LectorCSV --> FuenteEstatica

Filtrador --> Hecho: *
Filtrador --> Filtro: *

FiltrosColeccion *-- Filtro

Usuario *-- DatosPersonalesPublicador

FuenteDinamica --> Hecho: *
FuenteEstatica --> Hecho: *
FuenteProxy --> Hecho: *


'FormateadorHecho --> Filtro
'FormateadorHecho --> Hecho
'FormateadorHecho --> FiltrosColeccion
'FormateadorHecho --> BuscadorPais
'FormateadorHecho --> BuscadorCategoria
'FormateadorHecho --> FechaParser
'FormateadorHecho --> Pais
'FormateadorHecho --> Categoria
'FormateadorHecho --> TipoContenido
'FormateadorHecho --> Origen'

Geocodificador --> FuenteProxy
Geocodificador --> LectorCSV

BuscadorCategoria --> FuenteProxy
BuscadorCategoria --> FuenteEstatica
BuscadorCategoria --> FuenteDinamica

BuscadorPais --> FuenteProxy
BuscadorPais --> FuenteEstatica
BuscadorPais --> FuenteDinamica

Normalizador --> BuscadorPais
Normalizador --> BuscadorCategoria

FechaParser --> LectorCSV
FechaParser --> FuenteProxy

Mensaje --> Filtrador

Coleccion *-- AlgoritmoConsenso
Coleccion *-- Filtro

@enduml









class Administrador extends Visualizador {
    ' se almacenarán y quedarán a disposición de las personas administradoras.
    -listaContribuyentes: List<Contribuyente>
    'Subida manual del hecho
'    +subirHecho(hecho: Hecho)
'   +crearColeccion(datosColeccion: DatosColeccion, criterios: List<Filtro>, hechosTotales: List<Hecho>)
'   +importarHechos(fuente: Fuente)
'   +evaluarSolicitudEliminacion(solicitud: SolicitudHecho, respuesta: Boolean)
'   +evaluarSolicitudSubirHecho(solicitud: SolicitudHecho, respuesta: Boolean)
}



class aplicarFiltro{
}
' Agregar metodos, APLICAR FILTRO,...


class Contribuyente extends Visualizador {
    -cantHechosSubidos: Integer
    +incrementarHechosSubidos()
    +disminuirHechosSubidos()
    '+solicitarEliminacion(hecho: Hecho)
}



class Visualizador{
    -datosPersonales: DatosPersonalesPublicador
'    +solicitudSubirHecho(hecho: Hecho, GestorPersona: ContextoPersona)
    +navegarPorHechos(filtros: List<Filtro>, coleccion: Coleccion)
    +navegarPorHechos(coleccion: Coleccion)
    ' Llevarlo a clase
    -aplicarFiltros(filtros: List<Filtro>, coleccion: Coleccion): Set<Hecho>
}